/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class BajaCliente extends javax.swing.JPanel {

    /**
     * Creates new form BajaCliente
     */
    public BajaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        inputNameTxField = new javax.swing.JTextField();
        inputLastNameField = new javax.swing.JTextField();
        noCuentaLabel = new javax.swing.JLabel();
        inputNoCuentaTxField = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setText("Nombre");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 26, 67, 35));

        lastNameLabel.setText("Apellido");
        jPanel1.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 71, 77, -1));
        jPanel1.add(inputNameTxField, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 32, 200, -1));
        jPanel1.add(inputLastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 67, 200, -1));

        noCuentaLabel.setText("No. cuenta");
        jPanel1.add(noCuentaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 112, -1, -1));

        inputNoCuentaTxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNoCuentaTxFieldActionPerformed(evt);
            }
        });
        jPanel1.add(inputNoCuentaTxField, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 108, 200, -1));

        deleteBtn.setText("Eliminar");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 129, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -7, 420, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void inputNoCuentaTxFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNoCuentaTxFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNoCuentaTxFieldActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton deleteBtn;
    public javax.swing.JTextField inputLastNameField;
    public javax.swing.JTextField inputNameTxField;
    public javax.swing.JTextField inputNoCuentaTxField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel noCuentaLabel;
    // End of variables declaration//GEN-END:variables
}
